licenses(["notice"])

load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "UnitTestPatcher",
    module_name = "UnitTestPatcher",
    srcs = glob(["*.swift"]),
    visibility = ["//visibility:public"],
)
