name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened, ready_for_review]
      
jobs:
  build_darwin:
    name: Build Darwin
    runs-on: macos-latest
    strategy:
      matrix:
        xcode:
          - 12.4
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Bundle
      run: bundle install
    - name: Setup Keychain
      env:
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: bundle exec fastlane setup
    - name: Fetch Provisioning Profile
      env:
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }} 
        MATCH_REPO: ${{ secrets.MATCH_REPO }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      run: bundle exec fastlane certificates      
    - name: Build
      env:
      run: make build xcode=${{ matrix.xcode }}